sudo: required
dist: focal
language: python
cache: apt

env:
  global:
    - PYPI_USERNAME=pypy.wheelbuilder
    - CIBW_SKIP="pp* *-win32 *-manylinux_i686"
    - CIBW_PROJECT_REQUIRES_PYTHON=">3.6"
    - CIBW_BEFORE_BUILD_LINUX="yum install -y libunwind-devel elfutils-libelf-devel libdwarf-devel"
    - CIBW_BEFORE_TEST="pip install -r test_requirements.txt"
    - CIBW_TEST_COMMAND="cd {package} && pytest vmprof && pytest jitlog"
    - CIBW_TEST_COMMAND_WINDOWS="cd /d {package} && pytest vmprof && pytest jitlog"
    - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
    - CIBW_MANYLINUX_AARCH64_IMAGE=manylinux2014
    - CIBW_MANYLINUX_PPC64LE_IMAGE=manylinux2014

    # PYPI_PASSWORD
    - secure: "a5GdswXPW9TWytW5BfA5QZkdyrzgebecUNcbEmEXYkGPGp7rTFKVnRShD8+9YqH7swaZi9Xz/4YzBrZIkcXS0M+FJPo9sGYIccobZQ+KAlqbIE3N7cuWNLStqJDAj41BK9xxDtdKutJ95q+8iO9BLx+Iw6Y62EN4+a4d3WbuoZ4="

jobs:
  include:
    - services: docker
      arch: arm64
    - services: docker
      arch: ppc64le
    #- services: docker
    #  no libunwind-devel
    #  arch: s390x

install:
  - python3 -m pip install cibuildwheel==2.1.3

script:
  # build the wheels, put them into './wheelhouse'
  # The environment variables above are passed into the docker
  # which builds and tests the code
  - python3 -m cibuildwheel --output-dir wheelhouse



