name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_binary_wheels:
    name: Build binary wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        env:
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686"
          CIBW_BEFORE_BUILD_LINUX: yum install -y libunwind-devel elfutils-libelf-devel libdwarf-devel
          CIBW_BEFORE_TEST: pip install -r test_requirements.txt
          CIBW_TEST_COMMAND: cd {package} && pytest vmprof && pytest jitlog
          CIBW_TEST_COMMAND_WINDOWS: cd /d {package} && pytest vmprof && pytest jitlog

      #- uses: actions/upload-artifact@v2
      #  with:
      #    path: ./wheelhouse/*.whl


  build_pypy_wheels:
    name: Build pypy wheels
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy-3.7'

      - name: Install system libraries
        run: sudo apt install -y libunwind-dev libelf-dev libdwarf-dev

      - name: Build wheel
        run: |
          pypy -m pip install wheel
          pypy -m pip wheel .

      - name: Install wheel
        run: pypy -m pip install vmprof*.whl

      - name: Test wheel
        run: |
          pypy -m pip install -r test_requirements.txt
          pypy -m pytest vmprof
          pypy -m pytest jitlog
      # Uh-oh. packaging.tags does not support a pp3-none-any wheel tag.
      # The wheel name is something like
      # vmprof-0.4.15-py3-none-any.whl
      # when it should be
      # vmprof-0.4.15-pp3-none-any.whl

